
(live-load-config-file "emms-conf")
(live-load-config-file "emms-browser-conf")
(live-load-config-file "emms-cache-conf")
(live-load-config-file "emms-info-conf")
(live-load-config-file "emms-lyrics-conf")
(live-load-config-file "emms-iselect-conf")
(live-load-config-file "emms-mode-line-conf")
(live-load-config-file "emms-volume-conf")
(live-load-config-file "emms-lastfm-conf")
