(require 'em-smart)
(setq eshell-where-to-jump 'begin)
(setq eshell-review-quick-commands nil)
(setq eshell-smart-space-goes-to-end t)
(eshell-smart-initialize)
(remove-hook 'window-configuration-change-hook 'eshell-refresh-windows)
