(when (not (or (eq 'ms-dos system-type)
               (eq 'windows-nt system-type)))
  (live-load-config-file "auto-compile-conf"))

;; (require 'dircolors)
(require 'smooth-scrolling)
;; (require 'buffer-move)
(require 'find-file-in-project)

(live-load-config-file "backup-dir-conf")
(live-load-config-file "util-fns")
(live-load-config-file "built-in")
(live-load-config-file "cosmetic")
(live-load-config-file "ido-conf")
(live-load-config-file "smex-conf")
(live-load-config-file "tramp-conf")
(live-load-config-file "mouse-conf")
;; (live-load-config-file "ibuffer-git-conf")
(live-load-config-file "key-chord-conf")
;; (live-load-config-file "window-number-conf")
(live-load-config-file "recentf-conf")
(live-load-config-file "elisp-slime-nav-conf")
;; (live-load-config-file "popwin-conf")
;; (live-load-config-file "shell-conf")
(live-load-config-file "spelling-conf")
(live-load-config-file "lisp-conf")
;; (live-load-config-file "win-switch-conf")
;; (live-load-config-file "zone-conf")
(live-load-config-file "monkey-patch")
(live-load-config-file "package-conf")
(live-load-config-file "elscreen-conf")
(live-load-config-file "mode-line-frame-conf")
(live-load-config-file "whitespace-conf.el")
(live-load-config-file "org-mode-conf.el")

(windmove-default-keybindings)

(when (eq system-type 'darwin)
  (live-load-config-file "osx"))
